### ISSUE TITLE
Welcome Page Enhancements

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-vscode#166]
**Updated requirements**
- [x] There should be a setting for `Gauge: Welcome Page`. This should have multiple options for value. `Never show again`, `Show on upgrade`, `Show on new project load`. The default value is `Show on upgrade`.
- [x] The user can explicitly open it from the Command Pallet irrespective of the setting.
- [x] If the Welcome Page is open and project is reloaded it should still show up.

**Comment by sguptatw** [comment]
- Remove the `Toggle display of Welcome Page` - with the above feature it will be a setting with multiple values
- Remove the check box `Do not show this page until the next release` on the Welcome Page

**Comment by Apoorva-GA** [comment]
Should be available in nightly >= 10/03/18

**Comment by sguptatw** [comment]
- If the user explicitly opens the Welcome Page, on reload the Welcome Page should still be open. But currently it closes the Page
OS Windows

**Comment by Apoorva-GA** [comment]
Should be fixed as part of https://github.com/getgauge/gauge-vscode/issues/198.
Fix should be available in gauge-vscode nightly >= 15/03/18

**Comment by sguptatw** [comment]
The issue is still replicable in version gauge-0.0.4.nightly-2018-03-16.vsix

**Comment by Apoorva-GA** [comment]
This works fine with vscode nightly = 16/03/18.

Note : Please check if welcome page is enabled.
