### ISSUE TITLE
command 'gauge.createProject' not found

### ISSUE THREAD

**Issue by nathanBrenner** [getgauge/gauge-vscode#417]
Might seem like a repeat of #374 but the conditions are a little different.

`gauge -v`: 
```
Gauge version: 1.0.7

Plugins
-------
No plugins found
Plugins can be installed with `gauge install {plugin-name}`
```

Gauge-vscode extension version: 0.0.11
vscode version:
```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```
nodejs version: 10.16.3
Which os you are working on: macOS Mojave 10.14.6

Also: https://docs.gauge.org/getting_started/create-test-project.html?os=macos&language=javascript&ide=vscode
LTS of node is not currently 10.16.3, its 12.16.0

![Screen Shot 2020-02-13 at 2 26 16 PM](https://user-images.githubusercontent.com/9688337/74484147-e5f9a880-4e6c-11ea-96d4-d60ba1946a86.png)
![Screen Shot 2020-02-13 at 2 26 24 PM](https://user-images.githubusercontent.com/9688337/74484154-e7c36c00-4e6c-11ea-98db-f0ee21717901.png)
![Screen Shot 2020-02-13 at 2 26 49 PM](https://user-images.githubusercontent.com/9688337/74484157-e7c36c00-4e6c-11ea-941e-12c2c30f6e81.png)

**Comment by speeeeeed2006** [comment]
Same issus for me with the same os and same gauge version

**Comment by sriv** [comment]
@getgauge/core - can someone with macOS please check. This works for me on Linux

**Comment by negiDharmendra** [comment]
@speeeeeed2006 @nathanBrenner When there are no plugins `gauge --version --machine-readable` does not ouput a valid json which causes the JSON parsing to fail https://github.com/getgauge/gauge-vscode/blob/9eae898fa45215b26521d86da5b59d5dae3747d8/src/cli.ts#L32

Please make sure that you have installed one plugin at-least.

**Comment by speeeeeed2006** [comment]
Today it work. I think the restart of the Mac have helped.

**Comment by nathanBrenner** [comment]
@negiDharmendra Adding a plugin resolved this for me. Seems like that's a critical missing part in the docs. Review or change #301

**Comment by negiDharmendra** [comment]
@nathanBrenner I am going to close [this PR](https://github.com/getgauge/docs.gauge.org/pull/301) as this should be handled properly by Gauge and Gauge Vscode.

We have already pushed a fix to handle the actual issue in #418

**Comment by ipiyush25** [comment]
I am still facing same issue in newer gauge extension version.
Getting "Command 'Gauge: Create a new Gauge Project' resulted in an error (command 'gauge.createProject' not found)"

`Gauge version: 1.0.6
Gauge extension: 0.0.12
`

![image](https://user-images.githubusercontent.com/63631211/79190688-860a8880-7e42-11ea-84f7-5f4342e16a24.png)

**Comment by mguerrero2** [comment]
I am facing teh same issue here today.   

- gauge -v

Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
js (2.3.10)

- VS Code v1.44.1
- Windows 10.1.18363

<img width="204" alt="gauge" src="https://user-images.githubusercontent.com/38797566/79353346-f11e9280-7f08-11ea-874e-baeb504d6ae1.png">

**Comment by sriv** [comment]
This should have been fixed with gauge-vscode `0.0.13` - please update and try.
